name : Bewizor API Conatiner

resources:
  repositories:
  - repository: self
    type: git

variables:
  - name: DOCKER_REPOSITORY
    value: $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(DOCKER_REPOSITORY_NAME)

jobs:
- job: CreateDockerImageJob
  displayName: Create Image
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
  - script: |
      aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com
    displayName: 'Login to AWS'
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: $(DOCKER_REPOSITORY)
      command: buildAndPush
      Dockerfile: api/Dockerfile
      tags: |
        latest
        '$(Build.BuildId)'
